comment out release reporting

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -158,56 +158,56 @@ jobs:
           name: release
           path: release/
 
-  publish-tauri:
-    needs: sign-tauri
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: release
-          path: release
-      - uses: shallwefootball/s3-upload-action@master
-        name: Upload To S3
-        id: S3
-        with:
-          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
-          aws_bucket: "releases.gitbutler.com"
-          source_dir: "release/"
-          destination_dir: "releases/${{ env.channel }}/${{ env.version }}-${{ github.run_number }}"
-
-      # tell our server to update with the version number
-      - name: Tell our server to update
-        shell: bash
-        run: |
-          curl 'https://app.gitbutler.com/api/releases' \
-            --fail \
-            --request POST \
-            --header 'Content-Type: application/json' \
-            --header 'X-Auth-Token: ${{ secrets.BOT_AUTH_TOKEN }}' \
-            --data '{"channel":"${{ env.channel }}","version":"${{ env.version }}-${{ github.run_number }}","sha":"${{ github.sha }}"}'
-
-      - name: Tag release
-        shell: bash
-        env:
-          TAG_NAME: "${{ env.channel }}/${{ env.version }}"
-        run: |
-          function tag_exists() {
-            git tag --list | grep -q "^$1$"
-          }
-          function fetch_tag() {
-            git fetch origin "refs/tags/$1:refs/tags/$1"
-          }
-          function delete_tag() {
-            git push --delete origin "$1"
-          }
-          function create_tag() {
-            git tag --force "$1"
-            git push --tags
-          }
-
-          fetch_tag "$TAG_NAME" || true
-          if tag_exists "$TAG_NAME"; then
-            delete_tag "$TAG_NAME"
-          fi
-          create_tag "$TAG_NAME"
+#  publish-tauri:
+#    needs: sign-tauri
+#    steps:
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v2
+#        with:
+#          name: release
+#          path: release
+#      - uses: shallwefootball/s3-upload-action@master
+#        name: Upload To S3
+#        id: S3
+#        with:
+#          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
+#          aws_bucket: "releases.gitbutler.com"
+#          source_dir: "release/"
+#          destination_dir: "releases/${{ env.channel }}/${{ env.version }}-${{ github.run_number }}"
+#
+#      # tell our server to update with the version number
+#      - name: Tell our server to update
+#        shell: bash
+#        run: |
+#          curl 'https://app.gitbutler.com/api/releases' \
+#            --fail \
+#            --request POST \
+#            --header 'Content-Type: application/json' \
+#            --header 'X-Auth-Token: ${{ secrets.BOT_AUTH_TOKEN }}' \
+#            --data '{"channel":"${{ env.channel }}","version":"${{ env.version }}-${{ github.run_number }}","sha":"${{ github.sha }}"}'
+#
+#      - name: Tag release
+#        shell: bash
+#        env:
+#          TAG_NAME: "${{ env.channel }}/${{ env.version }}"
+#        run: |
+#          function tag_exists() {
+#            git tag --list | grep -q "^$1$"
+#          }
+#          function fetch_tag() {
+#            git fetch origin "refs/tags/$1:refs/tags/$1"
+#          }
+#          function delete_tag() {
+#            git push --delete origin "$1"
+#          }
+#          function create_tag() {
+#            git tag --force "$1"
+#            git push --tags
+#          }
+#
+#          fetch_tag "$TAG_NAME" || true
+#          if tag_exists "$TAG_NAME"; then
+#            delete_tag "$TAG_NAME"
+#          fi
+#          create_tag "$TAG_NAME"
